name: Docker CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  schedule:
    - cron:  '15 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Docker
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_TOKEN}}
    - name: Checkout Main
      uses: actions/checkout@v4
      with:
        ref: master
    - name: Set Version
      run: |
        echo "ITSM_VERSION=$(wget --quiet --no-cookies https://hub.docker.com/v2/namespaces/jetbrains/repositories/youtrack/tags?page_size=1 -O - | jq -c '.results[].name' | tr -d \")" >> $GITHUB_ENV
    - name: Build Custom
      run: |
        docker build . -f custom.dockerfile --pull --build-arg VERSION=22.0.4 --build-arg ITSM_VERSION=${{ env.ITSM_VERSION }} --tag bshp/itsm:${{ env.ITSM_VERSION }} --no-cache
    - name: Push Custom
      run: |
        docker push bshp/itsm:${{ env.ITSM_VERSION }}
    - name: Build Jetbrains
      run: |
        docker build . -f jetbrains.dockerfile --pull --build-arg ITSM_VERSION=${{ env.ITSM_VERSION }} --tag bshp/itsm:latest  --no-cache
    - name: Push Jetbrains
      run: |
        docker push bshp/itsm:latest
