name: Docker CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  schedule:
    - cron:  '15 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Docker
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_TOKEN}}
    - name: Checkout Main
      uses: actions/checkout@v4
      with:
        ref: master
    - name: Build Source
      run: |
        docker build . --pull --tag bshp/youtrack:tmp --progress=plain --no-cache 2>&1 | tee /tmp/build.output
        echo "TAG_NAME=$(cat /tmp/build.output | grep -oP '(?<=TAG_VERSION\:)(\d+\.\d+\.\d+)$')" >> $GITHUB_ENV
    - name: Push Source
      run: |
        docker tag youtrack:tmp bshp/youtrack:"${{ env.TAG_NAME }}"
        docker push bshp/youtrack:"${{ env.TAG_NAME }}"
    - name: Checkout Registry
      uses: actions/checkout@v4
      with:
        ref: registry
    - name: Build Jetbrains
      run: |
        docker build . --pull --tag bshp/youtrack:latest --progress=plain
    - name: Push Jetbrains
      run: |
        docker push bshp/youtrack:latest
